language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t brinduc/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true brinduc/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-west-2-028058238784"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
